name: cloud_resume_front_end
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public/ s3://matthewsechrist.cloud

    - name: Setup npm package
      run: npm init -y && npm install

    - name: set Cypress as a dev dependency
      run: npm install cypress --save-dev

    - name: Run Cypress tests
      uses: cypress-io/github-action@v2.9.7

