name: cloud_resume_front_end
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site assets to S3 bucket
      run: |
             aws s3 sync --size-only index.html s3://${{ secrets.AWS_S3_FRONT_END_BUCKET_NAME }}/index.html
             aws s3 sync --size-only assets/js/api.js s3://${{ secrets.AWS_S3_FRONT_END_BUCKET_NAME }}/assets/js/api.js
             aws s3 sync --size-only assets/css/style.css s3://${{ secrets.AWS_S3_FRONT_END_BUCKET_NAME }}/assets/css/style.css

